### ISSUE TITLE
Compile problem with cordova@5.2.0

### ISSUE THREAD

**Issue by amodoma** [manueldeveloper/cordova-plugin-volume-buttons#3]
Hi-

When compiling with cordova@5.2.0, the app did not build. The following method could not be resolved in VolumeButtonsListener.java:
this.webView.setOnKeyListener(this);

webView implements interface CordovaWebView, and this does not have the method.

This worked in cordova@3.5.0 when CordovaWebView extended WebView.

**Comment by manueldeveloper** [comment]
@amodoma you are totally right. Since I publish this plugin, I was working & studying at the same time and therefore I couldn't fix that bug when cordova been updated.

Now I've fixed the issue and the plugin is compatible with new versions of cordova without build errors.

Thanks!

**Comment by YamanSehzade** [comment]
Hi @manueldeveloper ,

Is it complete compatible with cordova 7.0.0 ?
